# Navigation Links

main:
  - name: Bio
    url: /
    weight: 10
  - name: Works
    url: project/
    weight: 11
  - name: Workshops
    url: workshops/
    weight: 12  
  - name: CV
    url: uploads/CV-Saito-2024.pdf
    weight: 13