# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: dark
  color: purple

# SEO
marketing:
  seo:
    site_type: Portfolio
    local_business_type: ''
    org_name: ''
    description: 'Clara Saito is a performance and visual artist based in Amsterdam. In her recent works she transitions between different characters.'
    twitter: ''
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    fixed_to_top: true 
    logo:
      filename: "logo.svg"
      #text: "Clara Saito"
    show_search: false
    show_theme_chooser: true
    highlight_active_link: true
    button:
      enable: true
      text: "Contact"
      url: "mailto:xcoxxnxtaxctx@claxxxraxxsaxitxxoxx.xcoxm"    

# Site footer
footer:
  block: minimal
  copyright:
    notice: '© {year} Clara Saito' 
    license:
      enable: true
      allow_derivatives: true
      share_alike: true
      allow_commercial: true

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'

# Site features
features:
  math:
    enable: false
  privacy_pack:
    enable: true
